export const EMOJI_SYMBOLS = {
  greetings: [
    { id: 1,  label: "Hello",        emoji: "👋",  color: "#FFE066" },
    { id: 2,  label: "Goodbye",      emoji: "🤝",  color: "#FFE066" },
    { id: 3,  label: "Please",       emoji: "🙏",  color: "#FFE066" },
    { id: 4,  label: "Thank You",    emoji: "😊",  color: "#FFE066" },
    { id: 5,  label: "Yes",          emoji: "✅",  color: "#FFE066" },
    { id: 6,  label: "No",           emoji: "❌",  color: "#FFE066" },
    { id: 7,  label: "Help",         emoji: "🆘",  color: "#FFE066" },
    { id: 8,  label: "Sorry",        emoji: "😔",  color: "#FFE066" },
    { id: 9,  label: "Good Morning", emoji: "🌅",  color: "#FFE066" },
    { id: 10, label: "Good Night",   emoji: "🌙",  color: "#FFE066" },
    { id: 11, label: "How Are You",  emoji: "🤗",  color: "#FFE066" },
    { id: 12, label: "I'm Fine",     emoji: "👍",  color: "#FFE066" },
    { id: 13, label: "Wait",         emoji: "✋",  color: "#FFE066" },
    { id: 14, label: "Stop",         emoji: "🛑",  color: "#FFE066" },
    { id: 15, label: "Come Here",    emoji: "👆",  color: "#FFE066" },
    { id: 16, label: "Look",         emoji: "👀",  color: "#FFE066" },
    { id: 17, label: "Listen",       emoji: "👂",  color: "#FFE066" },
    { id: 18, label: "I Don't Know", emoji: "🤷",  color: "#FFE066" },
    { id: 19, label: "More",         emoji: "➕",  color: "#FFE066" },
    { id: 20, label: "Finished",     emoji: "🏁",  color: "#FFE066" },
  ],
  feelings: [
    { id: 101, label: "Happy",       emoji: "😄", color: "#FF9F66" },
    { id: 102, label: "Sad",         emoji: "😢", color: "#FF9F66" },
    { id: 103, label: "Angry",       emoji: "😠", color: "#FF9F66" },
    { id: 104, label: "Scared",      emoji: "😨", color: "#FF9F66" },
    { id: 105, label: "Tired",       emoji: "😴", color: "#FF9F66" },
    { id: 106, label: "Excited",     emoji: "🤩", color: "#FF9F66" },
    { id: 107, label: "Confused",    emoji: "😕", color: "#FF9F66" },
    { id: 108, label: "Sick",        emoji: "🤒", color: "#FF9F66" },
    { id: 109, label: "Bored",       emoji: "😑", color: "#FF9F66" },
    { id: 110, label: "Loved",       emoji: "🥰", color: "#FF9F66" },
    { id: 111, label: "Frustrated",  emoji: "😤", color: "#FF9F66" },
    { id: 112, label: "Surprised",   emoji: "😲", color: "#FF9F66" },
    { id: 113, label: "Proud",       emoji: "😎", color: "#FF9F66" },
    { id: 114, label: "Nervous",     emoji: "😬", color: "#FF9F66" },
    { id: 115, label: "Calm",        emoji: "😌", color: "#FF9F66" },
    { id: 116, label: "Silly",       emoji: "🤪", color: "#FF9F66" },
    { id: 117, label: "Worried",     emoji: "😟", color: "#FF9F66" },
    { id: 118, label: "Disgusted",   emoji: "🤢", color: "#FF9F66" },
    { id: 119, label: "Hungry",      emoji: "🍽️", color: "#FF9F66" },
    { id: 120, label: "Thirsty",     emoji: "🥤", color: "#FF9F66" },
    { id: 121, label: "Hot",         emoji: "🥵", color: "#FF9F66" },
    { id: 122, label: "Cold",        emoji: "🥶", color: "#FF9F66" },
    { id: 123, label: "In Pain",     emoji: "😣", color: "#FF9F66" },
    { id: 124, label: "Lonely",      emoji: "🥺", color: "#FF9F66" },
  ],
  food: [
    { id: 201, label: "Breakfast",   emoji: "🍳",  color: "#FCA5A5" },
    { id: 202, label: "Lunch",       emoji: "🥗",  color: "#FCA5A5" },
    { id: 203, label: "Dinner",      emoji: "🍽️", color: "#FCA5A5" },
    { id: 204, label: "Snack",       emoji: "🍿",  color: "#FCA5A5" },
    { id: 205, label: "Apple",       emoji: "🍎",  color: "#FCA5A5" },
    { id: 206, label: "Banana",      emoji: "🍌",  color: "#FCA5A5" },
    { id: 207, label: "Orange",      emoji: "🍊",  color: "#FCA5A5" },
    { id: 208, label: "Grapes",      emoji: "🍇",  color: "#FCA5A5" },
    { id: 209, label: "Strawberry",  emoji: "🍓",  color: "#FCA5A5" },
    { id: 210, label: "Bread",       emoji: "🍞",  color: "#FCA5A5" },
    { id: 211, label: "Sandwich",    emoji: "🥪",  color: "#FCA5A5" },
    { id: 212, label: "Pizza",       emoji: "🍕",  color: "#FCA5A5" },
    { id: 213, label: "Burger",      emoji: "🍔",  color: "#FCA5A5" },
    { id: 214, label: "Pasta",       emoji: "🍝",  color: "#FCA5A5" },
    { id: 215, label: "Soup",        emoji: "🍜",  color: "#FCA5A5" },
    { id: 216, label: "Rice",        emoji: "🍚",  color: "#FCA5A5" },
    { id: 217, label: "Chicken",     emoji: "🍗",  color: "#FCA5A5" },
    { id: 218, label: "Salad",       emoji: "🥙",  color: "#FCA5A5" },
    { id: 219, label: "Eggs",        emoji: "🥚",  color: "#FCA5A5" },
    { id: 220, label: "Cheese",      emoji: "🧀",  color: "#FCA5A5" },
    { id: 221, label: "Yogurt",      emoji: "🫙",  color: "#FCA5A5" },
    { id: 222, label: "Cereal",      emoji: "🥣",  color: "#FCA5A5" },
    { id: 223, label: "Cookie",      emoji: "🍪",  color: "#FCA5A5" },
    { id: 224, label: "Cake",        emoji: "🎂",  color: "#FCA5A5" },
    { id: 225, label: "Ice Cream",   emoji: "🍦",  color: "#FCA5A5" },
    { id: 226, label: "Candy",       emoji: "🍬",  color: "#FCA5A5" },
    { id: 227, label: "Crackers",    emoji: "🫘",  color: "#FCA5A5" },
    { id: 228, label: "Hot Dog",     emoji: "🌭",  color: "#FCA5A5" },
    { id: 229, label: "Taco",        emoji: "🌮",  color: "#FCA5A5" },
    { id: 230, label: "Vegetables",  emoji: "🥦",  color: "#FCA5A5" },
  ],
  drinks: [
    { id: 301, label: "Water",        emoji: "💧", color: "#67E8F9" },
    { id: 302, label: "Milk",         emoji: "🥛", color: "#67E8F9" },
    { id: 303, label: "Orange Juice", emoji: "🍊", color: "#67E8F9" },
    { id: 304, label: "Apple Juice",  emoji: "🍎", color: "#67E8F9" },
    { id: 305, label: "Juice Box",    emoji: "🧃", color: "#67E8F9" },
    { id: 306, label: "Soda",         emoji: "🥤", color: "#67E8F9" },
    { id: 307, label: "Cola",         emoji: "🫙", color: "#67E8F9" },
    { id: 308, label: "Lemonade",     emoji: "🍋", color: "#67E8F9" },
    { id: 309, label: "Coffee",       emoji: "☕", color: "#67E8F9" },
    { id: 310, label: "Hot Coffee",   emoji: "🫖", color: "#67E8F9" },
    { id: 311, label: "Iced Coffee",  emoji: "🧊", color: "#67E8F9" },
    { id: 312, label: "Tea",          emoji: "🍵", color: "#67E8F9" },
    { id: 313, label: "Hot Tea",      emoji: "🍵", color: "#67E8F9" },
    { id: 314, label: "Iced Tea",     emoji: "🥤", color: "#67E8F9" },
    { id: 315, label: "Hot Cocoa",    emoji: "🍫", color: "#67E8F9" },
    { id: 316, label: "Smoothie",     emoji: "🫐", color: "#67E8F9" },
    { id: 317, label: "Milkshake",    emoji: "🥤", color: "#67E8F9" },
    { id: 318, label: "Sports Drink", emoji: "⚡", color: "#67E8F9" },
    { id: 319, label: "Sparkling",    emoji: "✨", color: "#67E8F9" },
    { id: 320, label: "Juice Drink",  emoji: "🍹", color: "#67E8F9" },
  ],
  daily: [
    { id: 401, label: "Wake Up",       emoji: "⏰",  color: "#86EFAC" },
    { id: 402, label: "Get Dressed",   emoji: "👕",  color: "#86EFAC" },
    { id: 403, label: "Brush Teeth",   emoji: "🪥",  color: "#86EFAC" },
    { id: 404, label: "Wash Hands",    emoji: "🧼",  color: "#86EFAC" },
    { id: 405, label: "Wash Face",     emoji: "🫧",  color: "#86EFAC" },
    { id: 406, label: "Comb Hair",     emoji: "💇",  color: "#86EFAC" },
    { id: 407, label: "Shower",        emoji: "🚿",  color: "#86EFAC" },
    { id: 408, label: "Bath",          emoji: "🛁",  color: "#86EFAC" },
    { id: 409, label: "Toilet",        emoji: "🚽",  color: "#86EFAC" },
    { id: 410, label: "Eat Meal",      emoji: "🍽️", color: "#86EFAC" },
    { id: 411, label: "Drink",         emoji: "🥤",  color: "#86EFAC" },
    { id: 412, label: "Take Medicine", emoji: "💊",  color: "#86EFAC" },
    { id: 413, label: "Nap Time",      emoji: "😴",  color: "#86EFAC" },
    { id: 414, label: "Bedtime",       emoji: "🛏️", color: "#86EFAC" },
    { id: 415, label: "Put on Shoes",  emoji: "👟",  color: "#86EFAC" },
    { id: 416, label: "Put on Coat",   emoji: "🧥",  color: "#86EFAC" },
    { id: 417, label: "Pack Bag",      emoji: "🎒",  color: "#86EFAC" },
    { id: 418, label: "Clean Up",      emoji: "🧹",  color: "#86EFAC" },
    { id: 419, label: "Laundry",       emoji: "🧺",  color: "#86EFAC" },
    { id: 420, label: "Make Bed",      emoji: "🛏️", color: "#86EFAC" },
    { id: 421, label: "Cook",          emoji: "👨‍🍳", color: "#86EFAC" },
    { id: 422, label: "Wash Dishes",   emoji: "🍽️", color: "#86EFAC" },
    { id: 423, label: "Grocery Shop",  emoji: "🛒",  color: "#86EFAC" },
    { id: 424, label: "Exercise",      emoji: "🏃",  color: "#86EFAC" },
    { id: 425, label: "Stretch",       emoji: "🧘",  color: "#86EFAC" },
    { id: 426, label: "Use Phone",     emoji: "📱",  color: "#86EFAC" },
    { id: 427, label: "Watch TV",      emoji: "📺",  color: "#86EFAC" },
    { id: 428, label: "Go Outside",    emoji: "🌳",  color: "#86EFAC" },
    { id: 429, label: "Lock Door",     emoji: "🔒",  color: "#86EFAC" },
    { id: 430, label: "Brush Hair",    emoji: "💆",  color: "#86EFAC" },
  ],
  health: [
    { id: 501, label: "Head Hurts",    emoji: "🤕",  color: "#FCD34D" },
    { id: 502, label: "Tummy Hurts",   emoji: "🤢",  color: "#FCD34D" },
    { id: 503, label: "Throat Hurts",  emoji: "😷",  color: "#FCD34D" },
    { id: 504, label: "Ear Hurts",     emoji: "👂",  color: "#FCD34D" },
    { id: 505, label: "Tooth Hurts",   emoji: "🦷",  color: "#FCD34D" },
    { id: 506, label: "Back Hurts",    emoji: "🦴",  color: "#FCD34D" },
    { id: 507, label: "Leg Hurts",     emoji: "🦵",  color: "#FCD34D" },
    { id: 508, label: "Arm Hurts",     emoji: "💪",  color: "#FCD34D" },
    { id: 509, label: "Dizzy",         emoji: "💫",  color: "#FCD34D" },
    { id: 510, label: "Nausea",        emoji: "🤮",  color: "#FCD34D" },
    { id: 511, label: "Fever",         emoji: "🌡️", color: "#FCD34D" },
    { id: 512, label: "Coughing",      emoji: "😮‍💨", color: "#FCD34D" },
    { id: 513, label: "Sneezing",      emoji: "🤧",  color: "#FCD34D" },
    { id: 514, label: "Itchy",         emoji: "😫",  color: "#FCD34D" },
    { id: 515, label: "Medicine",      emoji: "💊",  color: "#FCD34D" },
    { id: 516, label: "Doctor",        emoji: "👨‍⚕️", color: "#FCD34D" },
    { id: 517, label: "Hospital",      emoji: "🏥",  color: "#FCD34D" },
    { id: 518, label: "Ambulance",     emoji: "🚑",  color: "#FCD34D" },
    { id: 519, label: "Emergency",     emoji: "🆘",  color: "#FCD34D" },
    { id: 520, label: "Need Rest",     emoji: "🛌",  color: "#FCD34D" },
    { id: 521, label: "Tired/Fatigue", emoji: "😩",  color: "#FCD34D" },
    { id: 522, label: "Feeling Better",emoji: "😊",  color: "#FCD34D" },
    { id: 523, label: "Wheelchair",    emoji: "♿",  color: "#FCD34D" },
    { id: 524, label: "Therapy",       emoji: "🧠",  color: "#FCD34D" },
  ],
  leisure: [
    { id: 601, label: "Play",          emoji: "🎮",  color: "#A78BFA" },
    { id: 602, label: "Read Book",     emoji: "📚",  color: "#A78BFA" },
    { id: 603, label: "Draw",          emoji: "🎨",  color: "#A78BFA" },
    { id: 604, label: "Color",         emoji: "🖍️", color: "#A78BFA" },
    { id: 605, label: "Music",         emoji: "🎵",  color: "#A78BFA" },
    { id: 606, label: "Sing",          emoji: "🎤",  color: "#A78BFA" },
    { id: 607, label: "Dance",         emoji: "🕺",  color: "#A78BFA" },
    { id: 608, label: "Watch TV",      emoji: "📺",  color: "#A78BFA" },
    { id: 609, label: "Movie",         emoji: "🎬",  color: "#A78BFA" },
    { id: 610, label: "Puzzle",        emoji: "🧩",  color: "#A78BFA" },
    { id: 611, label: "Board Game",    emoji: "🎲",  color: "#A78BFA" },
    { id: 612, label: "Lego/Blocks",   emoji: "🧱",  color: "#A78BFA" },
    { id: 613, label: "Doll",          emoji: "🪆",  color: "#A78BFA" },
    { id: 614, label: "Ball",          emoji: "⚽",  color: "#A78BFA" },
    { id: 615, label: "Bike",          emoji: "🚲",  color: "#A78BFA" },
    { id: 616, label: "Swim",          emoji: "🏊",  color: "#A78BFA" },
    { id: 617, label: "Run",           emoji: "🏃",  color: "#A78BFA" },
    { id: 618, label: "Playground",    emoji: "🛝",  color: "#A78BFA" },
    { id: 619, label: "Park",          emoji: "🌿",  color: "#A78BFA" },
    { id: 620, label: "Animals",       emoji: "🐾",  color: "#A78BFA" },
    { id: 621, label: "Craft",         emoji: "✂️",  color: "#A78BFA" },
    { id: 622, label: "Computer",      emoji: "💻",  color: "#A78BFA" },
    { id: 623, label: "Video Game",    emoji: "🕹️", color: "#A78BFA" },
    { id: 624, label: "Tablet",        emoji: "📱",  color: "#A78BFA" },
  ],
  school: [
    { id: 701, label: "School",        emoji: "🏫",  color: "#60A5FA" },
    { id: 702, label: "Class",         emoji: "🏛️", color: "#60A5FA" },
    { id: 703, label: "Teacher",       emoji: "👩‍🏫", color: "#60A5FA" },
    { id: 704, label: "Student",       emoji: "🧑‍🎓", color: "#60A5FA" },
    { id: 705, label: "Backpack",      emoji: "🎒",  color: "#60A5FA" },
    { id: 706, label: "Pencil",        emoji: "✏️",  color: "#60A5FA" },
    { id: 707, label: "Book",          emoji: "📖",  color: "#60A5FA" },
    { id: 708, label: "Notebook",      emoji: "📓",  color: "#60A5FA" },
    { id: 709, label: "Math",          emoji: "🔢",  color: "#60A5FA" },
    { id: 710, label: "Reading",       emoji: "📚",  color: "#60A5FA" },
    { id: 711, label: "Writing",       emoji: "✍️",  color: "#60A5FA" },
    { id: 712, label: "Art",           emoji: "🎨",  color: "#60A5FA" },
    { id: 713, label: "Music Class",   emoji: "🎵",  color: "#60A5FA" },
    { id: 714, label: "Gym/PE",        emoji: "🏋️", color: "#60A5FA" },
    { id: 715, label: "Lunch Break",   emoji: "🍱",  color: "#60A5FA" },
    { id: 716, label: "Recess",        emoji: "🛝",  color: "#60A5FA" },
    { id: 717, label: "Bus",           emoji: "🚌",  color: "#60A5FA" },
    { id: 718, label: "Homework",      emoji: "📝",  color: "#60A5FA" },
    { id: 719, label: "Test",          emoji: "📋",  color: "#60A5FA" },
    { id: 720, label: "Computer Lab",  emoji: "💻",  color: "#60A5FA" },
    { id: 721, label: "Library",       emoji: "📚",  color: "#60A5FA" },
    { id: 722, label: "Nurse",         emoji: "🩺",  color: "#60A5FA" },
    { id: 723, label: "Principal",     emoji: "🧑‍💼", color: "#60A5FA" },
    { id: 724, label: "Cafeteria",     emoji: "🍽️", color: "#60A5FA" },
  ],
  places: [
    { id: 801, label: "Home",          emoji: "🏠",  color: "#34D399" },
    { id: 802, label: "Bedroom",       emoji: "🛏️", color: "#34D399" },
    { id: 803, label: "Kitchen",       emoji: "🍳",  color: "#34D399" },
    { id: 804, label: "Bathroom",      emoji: "🚿",  color: "#34D399" },
    { id: 805, label: "Living Room",   emoji: "🛋️", color: "#34D399" },
    { id: 806, label: "Backyard",      emoji: "🌱",  color: "#34D399" },
    { id: 807, label: "School",        emoji: "🏫",  color: "#34D399" },
    { id: 808, label: "Hospital",      emoji: "🏥",  color: "#34D399" },
    { id: 809, label: "Clinic",        emoji: "🩺",  color: "#34D399" },
    { id: 810, label: "Pharmacy",      emoji: "💊",  color: "#34D399" },
    { id: 811, label: "Grocery Store", emoji: "🛒",  color: "#34D399" },
    { id: 812, label: "Restaurant",    emoji: "🍽️", color: "#34D399" },
    { id: 813, label: "Park",          emoji: "🌿",  color: "#34D399" },
    { id: 814, label: "Playground",    emoji: "🛝",  color: "#34D399" },
    { id: 815, label: "Library",       emoji: "📚",  color: "#34D399" },
    { id: 816, label: "Church",        emoji: "⛪",  color: "#34D399" },
    { id: 817, label: "Gym",           emoji: "🏋️", color: "#34D399" },
    { id: 818, label: "Pool",          emoji: "🏊",  color: "#34D399" },
    { id: 819, label: "Beach",         emoji: "🏖️", color: "#34D399" },
    { id: 820, label: "Car",           emoji: "🚗",  color: "#34D399" },
    { id: 821, label: "Bus",           emoji: "🚌",  color: "#34D399" },
    { id: 822, label: "Airplane",      emoji: "✈️",  color: "#34D399" },
    { id: 823, label: "Dentist",       emoji: "🦷",  color: "#34D399" },
    { id: 824, label: "Therapy",       emoji: "🧠",  color: "#34D399" },
  ],
  people: [
    { id: 901, label: "Me",            emoji: "🙋",  color: "#F472B6" },
    { id: 902, label: "Mom",           emoji: "👩",  color: "#F472B6" },
    { id: 903, label: "Dad",           emoji: "👨",  color: "#F472B6" },
    { id: 904, label: "Grandma",       emoji: "👵",  color: "#F472B6" },
    { id: 905, label: "Grandpa",       emoji: "👴",  color: "#F472B6" },
    { id: 906, label: "Brother",       emoji: "👦",  color: "#F472B6" },
    { id: 907, label: "Sister",        emoji: "👧",  color: "#F472B6" },
    { id: 908, label: "Baby",          emoji: "👶",  color: "#F472B6" },
    { id: 909, label: "Family",        emoji: "👨‍👩‍👧‍👦", color: "#F472B6" },
    { id: 910, label: "Friend",        emoji: "🧑",  color: "#F472B6" },
    { id: 911, label: "Best Friend",   emoji: "🫂",  color: "#F472B6" },
    { id: 912, label: "Caregiver",     emoji: "🧑‍🦽", color: "#F472B6" },
    { id: 913, label: "Doctor",        emoji: "👨‍⚕️", color: "#F472B6" },
    { id: 914, label: "Nurse",         emoji: "👩‍⚕️", color: "#F472B6" },
    { id: 915, label: "Teacher",       emoji: "👩‍🏫", color: "#F472B6" },
    { id: 916, label: "Therapist",     emoji: "🧠",  color: "#F472B6" },
    { id: 917, label: "Neighbor",      emoji: "🏘️", color: "#F472B6" },
    { id: 918, label: "Classmate",     emoji: "🧑‍🎓", color: "#F472B6" },
    { id: 919, label: "Coach",         emoji: "🏅",  color: "#F472B6" },
    { id: 920, label: "Aunt",          emoji: "👩‍🦰", color: "#F472B6" },
    { id: 921, label: "Uncle",         emoji: "👨‍🦰", color: "#F472B6" },
    { id: 922, label: "Pet",           emoji: "🐶",  color: "#F472B6" },
  ],
  needs: [
    { id: 1001, label: "I Want",        emoji: "🫳", color: "#C4B5FD" },
    { id: 1002, label: "I Need",        emoji: "❗", color: "#C4B5FD" },
    { id: 1003, label: "I Like",        emoji: "❤️", color: "#C4B5FD" },
    { id: 1004, label: "I Don't Like",  emoji: "👎", color: "#C4B5FD" },
    { id: 1005, label: "Give Me",       emoji: "🙌", color: "#C4B5FD" },
    { id: 1006, label: "Take Away",     emoji: "↩️", color: "#C4B5FD" },
    { id: 1007, label: "Too Loud",      emoji: "🔇", color: "#C4B5FD" },
    { id: 1008, label: "Too Quiet",     emoji: "🔊", color: "#C4B5FD" },
    { id: 1009, label: "Too Hot",       emoji: "🔥", color: "#C4B5FD" },
    { id: 1010, label: "Too Cold",      emoji: "❄️", color: "#C4B5FD" },
    { id: 1011, label: "Comfortable",   emoji: "😌", color: "#C4B5FD" },
    { id: 1012, label: "Uncomfortable", emoji: "😫", color: "#C4B5FD" },
    { id: 1013, label: "Turn On",       emoji: "💡", color: "#C4B5FD" },
    { id: 1014, label: "Turn Off",      emoji: "🌑", color: "#C4B5FD" },
    { id: 1015, label: "Open",          emoji: "🔓", color: "#C4B5FD" },
    { id: 1016, label: "Close",         emoji: "🔐", color: "#C4B5FD" },
    { id: 1017, label: "Sit Down",      emoji: "🪑", color: "#C4B5FD" },
    { id: 1018, label: "Stand Up",      emoji: "🧍", color: "#C4B5FD" },
    { id: 1019, label: "Lie Down",      emoji: "🛌", color: "#C4B5FD" },
    { id: 1020, label: "Go Away",       emoji: "🚷", color: "#C4B5FD" },
    { id: 1021, label: "Come Back",     emoji: "↩️", color: "#C4B5FD" },
    { id: 1022, label: "Hug Me",        emoji: "🤗", color: "#C4B5FD" },
    { id: 1023, label: "Leave Me",      emoji: "✋", color: "#C4B5FD" },
    { id: 1024, label: "Change It",     emoji: "🔄", color: "#C4B5FD" },
  ],
};

export const getAllSymbols = () => Object.values(EMOJI_SYMBOLS).flat();
