export const EMOJI_SYMBOLS = {

  // ── Greetings (1–99) ─────────────────────────────────────────
  greetings: [
    { id: 1,  label: "Hello",            emoji: "👋",  color: "#FFE066" },
    { id: 2,  label: "Goodbye",          emoji: "🤝",  color: "#FFE066" },
    { id: 3,  label: "Please",           emoji: "🙏",  color: "#FFE066" },
    { id: 4,  label: "Thank You",        emoji: "😊",  color: "#FFE066" },
    { id: 5,  label: "Yes",              emoji: "✅",  color: "#FFE066" },
    { id: 6,  label: "No",               emoji: "❌",  color: "#FFE066" },
    { id: 7,  label: "Help",             emoji: "🆘",  color: "#FFE066" },
    { id: 8,  label: "Sorry",            emoji: "😔",  color: "#FFE066" },
    { id: 9,  label: "Good Morning",     emoji: "🌅",  color: "#FFE066" },
    { id: 10, label: "Good Night",       emoji: "🌙",  color: "#FFE066" },
    { id: 11, label: "How Are You",      emoji: "🤗",  color: "#FFE066" },
    { id: 12, label: "I'm Fine",         emoji: "👍",  color: "#FFE066" },
    { id: 13, label: "Wait",             emoji: "✋",  color: "#FFE066" },
    { id: 14, label: "Stop",             emoji: "🛑",  color: "#FFE066" },
    { id: 15, label: "Come Here",        emoji: "👆",  color: "#FFE066" },
    { id: 16, label: "Look",             emoji: "👀",  color: "#FFE066" },
    { id: 17, label: "Listen",           emoji: "👂",  color: "#FFE066" },
    { id: 18, label: "I Don't Know",     emoji: "🤷",  color: "#FFE066" },
    { id: 19, label: "More",             emoji: "➕",  color: "#FFE066" },
    { id: 20, label: "Finished",         emoji: "🏁",  color: "#FFE066" },
    { id: 21, label: "You're Welcome",   emoji: "🫶",  color: "#FFE066" },
    { id: 22, label: "Excuse Me",        emoji: "🙋",  color: "#FFE066" },
    { id: 23, label: "Nice To Meet You", emoji: "🤝",  color: "#FFE066" },
    { id: 24, label: "See You Later",    emoji: "👋",  color: "#FFE066" },
    { id: 25, label: "Good Afternoon",   emoji: "☀️",  color: "#FFE066" },
    { id: 26, label: "Good Evening",     emoji: "🌆",  color: "#FFE066" },
    { id: 27, label: "I Love You",       emoji: "❤️",  color: "#FFE066" },
    { id: 28, label: "Happy Birthday",   emoji: "🎂",  color: "#FFE066" },
    { id: 29, label: "Congratulations",  emoji: "🎉",  color: "#FFE066" },
    { id: 30, label: "Please Repeat",    emoji: "🔁",  color: "#FFE066" },
    { id: 31, label: "I Agree",          emoji: "👌",  color: "#FFE066" },
    { id: 32, label: "I Disagree",       emoji: "🙅",  color: "#FFE066" },
    { id: 33, label: "Maybe",            emoji: "🤔",  color: "#FFE066" },
    { id: 34, label: "Not Sure",         emoji: "😐",  color: "#FFE066" },
  ],

  // ── Feelings (101–199) ────────────────────────────────────────
  feelings: [
    { id: 101, label: "Happy",           emoji: "😄",  color: "#FF9F66" },
    { id: 102, label: "Sad",             emoji: "😢",  color: "#FF9F66" },
    { id: 103, label: "Angry",           emoji: "😠",  color: "#FF9F66" },
    { id: 104, label: "Scared",          emoji: "😨",  color: "#FF9F66" },
    { id: 105, label: "Tired",           emoji: "😴",  color: "#FF9F66" },
    { id: 106, label: "Excited",         emoji: "🤩",  color: "#FF9F66" },
    { id: 107, label: "Confused",        emoji: "😕",  color: "#FF9F66" },
    { id: 108, label: "Sick",            emoji: "🤒",  color: "#FF9F66" },
    { id: 109, label: "Bored",           emoji: "😑",  color: "#FF9F66" },
    { id: 110, label: "Loved",           emoji: "🥰",  color: "#FF9F66" },
    { id: 111, label: "Frustrated",      emoji: "😤",  color: "#FF9F66" },
    { id: 112, label: "Surprised",       emoji: "😲",  color: "#FF9F66" },
    { id: 113, label: "Proud",           emoji: "😎",  color: "#FF9F66" },
    { id: 114, label: "Nervous",         emoji: "😬",  color: "#FF9F66" },
    { id: 115, label: "Calm",            emoji: "😌",  color: "#FF9F66" },
    { id: 116, label: "Silly",           emoji: "🤪",  color: "#FF9F66" },
    { id: 117, label: "Worried",         emoji: "😟",  color: "#FF9F66" },
    { id: 118, label: "Disgusted",       emoji: "🤢",  color: "#FF9F66" },
    { id: 119, label: "Hungry",          emoji: "🍽️", color: "#FF9F66" },
    { id: 120, label: "Thirsty",         emoji: "🥤",  color: "#FF9F66" },
    { id: 121, label: "Hot",             emoji: "🥵",  color: "#FF9F66" },
    { id: 122, label: "Cold",            emoji: "🥶",  color: "#FF9F66" },
    { id: 123, label: "In Pain",         emoji: "😣",  color: "#FF9F66" },
    { id: 124, label: "Lonely",          emoji: "🥺",  color: "#FF9F66" },
    { id: 125, label: "Embarrassed",     emoji: "😳",  color: "#FF9F66" },
    { id: 126, label: "Grateful",        emoji: "🙏",  color: "#FF9F66" },
    { id: 127, label: "Jealous",         emoji: "😒",  color: "#FF9F66" },
    { id: 128, label: "Hopeful",         emoji: "🌟",  color: "#FF9F66" },
    { id: 129, label: "Overwhelmed",     emoji: "😵",  color: "#FF9F66" },
    { id: 130, label: "Relaxed",         emoji: "😎",  color: "#FF9F66" },
    { id: 131, label: "Content",         emoji: "☺️",  color: "#FF9F66" },
    { id: 132, label: "Disappointed",    emoji: "😞",  color: "#FF9F66" },
    { id: 133, label: "Ashamed",         emoji: "😶",  color: "#FF9F66" },
    { id: 134, label: "Determined",      emoji: "💪",  color: "#FF9F66" },
    { id: 135, label: "Playful",         emoji: "🎉",  color: "#FF9F66" },
  ],

  // ── Food (201–299) ────────────────────────────────────────────
  food: [
    { id: 201, label: "Breakfast",       emoji: "🍳",  color: "#FCA5A5" },
    { id: 202, label: "Lunch",           emoji: "🥗",  color: "#FCA5A5" },
    { id: 203, label: "Dinner",          emoji: "🍽️", color: "#FCA5A5" },
    { id: 204, label: "Snack",           emoji: "🍿",  color: "#FCA5A5" },
    { id: 205, label: "Apple",           emoji: "🍎",  color: "#FCA5A5" },
    { id: 206, label: "Banana",          emoji: "🍌",  color: "#FCA5A5" },
    { id: 207, label: "Orange",          emoji: "🍊",  color: "#FCA5A5" },
    { id: 208, label: "Grapes",          emoji: "🍇",  color: "#FCA5A5" },
    { id: 209, label: "Strawberry",      emoji: "🍓",  color: "#FCA5A5" },
    { id: 210, label: "Bread",           emoji: "🍞",  color: "#FCA5A5" },
    { id: 211, label: "Sandwich",        emoji: "🥪",  color: "#FCA5A5" },
    { id: 212, label: "Pizza",           emoji: "🍕",  color: "#FCA5A5" },
    { id: 213, label: "Burger",          emoji: "🍔",  color: "#FCA5A5" },
    { id: 214, label: "Pasta",           emoji: "🍝",  color: "#FCA5A5" },
    { id: 215, label: "Soup",            emoji: "🍜",  color: "#FCA5A5" },
    { id: 216, label: "Rice",            emoji: "🍚",  color: "#FCA5A5" },
    { id: 217, label: "Chicken",         emoji: "🍗",  color: "#FCA5A5" },
    { id: 218, label: "Salad",           emoji: "🥙",  color: "#FCA5A5" },
    { id: 219, label: "Eggs",            emoji: "🥚",  color: "#FCA5A5" },
    { id: 220, label: "Cheese",          emoji: "🧀",  color: "#FCA5A5" },
    { id: 221, label: "Yogurt",          emoji: "🫙",  color: "#FCA5A5" },
    { id: 222, label: "Cereal",          emoji: "🥣",  color: "#FCA5A5" },
    { id: 223, label: "Cookie",          emoji: "🍪",  color: "#FCA5A5" },
    { id: 224, label: "Cake",            emoji: "🎂",  color: "#FCA5A5" },
    { id: 225, label: "Ice Cream",       emoji: "🍦",  color: "#FCA5A5" },
    { id: 226, label: "Candy",           emoji: "🍬",  color: "#FCA5A5" },
    { id: 227, label: "Crackers",        emoji: "🫘",  color: "#FCA5A5" },
    { id: 228, label: "Hot Dog",         emoji: "🌭",  color: "#FCA5A5" },
    { id: 229, label: "Taco",            emoji: "🌮",  color: "#FCA5A5" },
    { id: 230, label: "Vegetables",      emoji: "🥦",  color: "#FCA5A5" },
    { id: 231, label: "Carrot",          emoji: "🥕",  color: "#FCA5A5" },
    { id: 232, label: "Corn",            emoji: "🌽",  color: "#FCA5A5" },
    { id: 233, label: "Potato",          emoji: "🥔",  color: "#FCA5A5" },
    { id: 234, label: "Tomato",          emoji: "🍅",  color: "#FCA5A5" },
    { id: 235, label: "Watermelon",      emoji: "🍉",  color: "#FCA5A5" },
    { id: 236, label: "Blueberries",     emoji: "🫐",  color: "#FCA5A5" },
    { id: 237, label: "Mango",           emoji: "🥭",  color: "#FCA5A5" },
    { id: 238, label: "Peach",           emoji: "🍑",  color: "#FCA5A5" },
    { id: 239, label: "Peanut Butter",   emoji: "🥜",  color: "#FCA5A5" },
    { id: 240, label: "Pancakes",        emoji: "🥞",  color: "#FCA5A5" },
    { id: 241, label: "Waffles",         emoji: "🧇",  color: "#FCA5A5" },
    { id: 242, label: "Oatmeal",         emoji: "🥣",  color: "#FCA5A5" },
    { id: 243, label: "Fish",            emoji: "🐟",  color: "#FCA5A5" },
    { id: 244, label: "Beans",           emoji: "🫘",  color: "#FCA5A5" },
    { id: 245, label: "Fries",           emoji: "🍟",  color: "#FCA5A5" },
    { id: 246, label: "Popcorn",         emoji: "🍿",  color: "#FCA5A5" },
    { id: 247, label: "Donut",           emoji: "🍩",  color: "#FCA5A5" },
    { id: 248, label: "Chocolate",       emoji: "🍫",  color: "#FCA5A5" },
  ],

  // ── Drinks (301–399) ─────────────────────────────────────────
  drinks: [
    { id: 301, label: "Water",           emoji: "💧",  color: "#67E8F9" },
    { id: 302, label: "Milk",            emoji: "🥛",  color: "#67E8F9" },
    { id: 303, label: "Orange Juice",    emoji: "🍊",  color: "#67E8F9" },
    { id: 304, label: "Apple Juice",     emoji: "🍎",  color: "#67E8F9" },
    { id: 305, label: "Juice Box",       emoji: "🧃",  color: "#67E8F9" },
    { id: 306, label: "Soda",            emoji: "🥤",  color: "#67E8F9" },
    { id: 307, label: "Cola",            emoji: "🫙",  color: "#67E8F9" },
    { id: 308, label: "Lemonade",        emoji: "🍋",  color: "#67E8F9" },
    { id: 309, label: "Coffee",          emoji: "☕",  color: "#67E8F9" },
    { id: 310, label: "Hot Coffee",      emoji: "🫖",  color: "#67E8F9" },
    { id: 311, label: "Iced Coffee",     emoji: "🧊",  color: "#67E8F9" },
    { id: 312, label: "Tea",             emoji: "🍵",  color: "#67E8F9" },
    { id: 313, label: "Hot Tea",         emoji: "🍵",  color: "#67E8F9" },
    { id: 314, label: "Iced Tea",        emoji: "🥤",  color: "#67E8F9" },
    { id: 315, label: "Hot Cocoa",       emoji: "🍫",  color: "#67E8F9" },
    { id: 316, label: "Smoothie",        emoji: "🫐",  color: "#67E8F9" },
    { id: 317, label: "Milkshake",       emoji: "🥤",  color: "#67E8F9" },
    { id: 318, label: "Sports Drink",    emoji: "⚡",  color: "#67E8F9" },
    { id: 319, label: "Sparkling",       emoji: "✨",  color: "#67E8F9" },
    { id: 320, label: "Juice Drink",     emoji: "🍹",  color: "#67E8F9" },
    { id: 321, label: "Warm Water",      emoji: "♨️",  color: "#67E8F9" },
    { id: 322, label: "Cold Water",      emoji: "🧊",  color: "#67E8F9" },
    { id: 323, label: "Grape Juice",     emoji: "🍇",  color: "#67E8F9" },
    { id: 324, label: "Coconut Water",   emoji: "🥥",  color: "#67E8F9" },
  ],

  // ── Daily Living (401–499) ────────────────────────────────────
  daily: [
    { id: 401, label: "Wake Up",         emoji: "⏰",  color: "#86EFAC" },
    { id: 402, label: "Get Dressed",     emoji: "👕",  color: "#86EFAC" },
    { id: 403, label: "Brush Teeth",     emoji: "🪥",  color: "#86EFAC" },
    { id: 404, label: "Wash Hands",      emoji: "🧼",  color: "#86EFAC" },
    { id: 405, label: "Wash Face",       emoji: "🫧",  color: "#86EFAC" },
    { id: 406, label: "Comb Hair",       emoji: "💇",  color: "#86EFAC" },
    { id: 407, label: "Shower",          emoji: "🚿",  color: "#86EFAC" },
    { id: 408, label: "Bath",            emoji: "🛁",  color: "#86EFAC" },
    { id: 409, label: "Toilet",          emoji: "🚽",  color: "#86EFAC" },
    { id: 410, label: "Eat Meal",        emoji: "🍽️", color: "#86EFAC" },
    { id: 411, label: "Drink",           emoji: "🥤",  color: "#86EFAC" },
    { id: 412, label: "Take Medicine",   emoji: "💊",  color: "#86EFAC" },
    { id: 413, label: "Nap Time",        emoji: "😴",  color: "#86EFAC" },
    { id: 414, label: "Bedtime",         emoji: "🛏️", color: "#86EFAC" },
    { id: 415, label: "Put on Shoes",    emoji: "👟",  color: "#86EFAC" },
    { id: 416, label: "Put on Coat",     emoji: "🧥",  color: "#86EFAC" },
    { id: 417, label: "Pack Bag",        emoji: "🎒",  color: "#86EFAC" },
    { id: 418, label: "Clean Up",        emoji: "🧹",  color: "#86EFAC" },
    { id: 419, label: "Laundry",         emoji: "🧺",  color: "#86EFAC" },
    { id: 420, label: "Make Bed",        emoji: "🛏️", color: "#86EFAC" },
    { id: 421, label: "Cook",            emoji: "👨‍🍳", color: "#86EFAC" },
    { id: 422, label: "Wash Dishes",     emoji: "🍽️", color: "#86EFAC" },
    { id: 423, label: "Grocery Shop",    emoji: "🛒",  color: "#86EFAC" },
    { id: 424, label: "Exercise",        emoji: "🏃",  color: "#86EFAC" },
    { id: 425, label: "Stretch",         emoji: "🧘",  color: "#86EFAC" },
    { id: 426, label: "Use Phone",       emoji: "📱",  color: "#86EFAC" },
    { id: 427, label: "Watch TV",        emoji: "📺",  color: "#86EFAC" },
    { id: 428, label: "Go Outside",      emoji: "🌳",  color: "#86EFAC" },
    { id: 429, label: "Lock Door",       emoji: "🔒",  color: "#86EFAC" },
    { id: 430, label: "Brush Hair",      emoji: "💆",  color: "#86EFAC" },
    { id: 431, label: "Get in Car",      emoji: "🚗",  color: "#86EFAC" },
    { id: 432, label: "Come Home",       emoji: "🏠",  color: "#86EFAC" },
    { id: 433, label: "Video Call",      emoji: "📹",  color: "#86EFAC" },
    { id: 434, label: "Take a Break",    emoji: "⏸️", color: "#86EFAC" },
    { id: 435, label: "Cut Nails",       emoji: "✂️",  color: "#86EFAC" },
    { id: 436, label: "Deodorant",       emoji: "🧴",  color: "#86EFAC" },
    { id: 437, label: "Sunscreen",       emoji: "☀️",  color: "#86EFAC" },
    { id: 438, label: "Change Clothes",  emoji: "🔄",  color: "#86EFAC" },
  ],

  // ── Health (501–599) ─────────────────────────────────────────
  health: [
    { id: 501, label: "Head Hurts",      emoji: "🤕",  color: "#FCD34D" },
    { id: 502, label: "Tummy Hurts",     emoji: "🤢",  color: "#FCD34D" },
    { id: 503, label: "Throat Hurts",    emoji: "😷",  color: "#FCD34D" },
    { id: 504, label: "Ear Hurts",       emoji: "👂",  color: "#FCD34D" },
    { id: 505, label: "Tooth Hurts",     emoji: "🦷",  color: "#FCD34D" },
    { id: 506, label: "Back Hurts",      emoji: "🦴",  color: "#FCD34D" },
    { id: 507, label: "Leg Hurts",       emoji: "🦵",  color: "#FCD34D" },
    { id: 508, label: "Arm Hurts",       emoji: "💪",  color: "#FCD34D" },
    { id: 509, label: "Dizzy",           emoji: "💫",  color: "#FCD34D" },
    { id: 510, label: "Nausea",          emoji: "🤮",  color: "#FCD34D" },
    { id: 511, label: "Fever",           emoji: "🌡️", color: "#FCD34D" },
    { id: 512, label: "Coughing",        emoji: "😮‍💨", color: "#FCD34D" },
    { id: 513, label: "Sneezing",        emoji: "🤧",  color: "#FCD34D" },
    { id: 514, label: "Itchy",           emoji: "😫",  color: "#FCD34D" },
    { id: 515, label: "Medicine",        emoji: "💊",  color: "#FCD34D" },
    { id: 516, label: "Doctor",          emoji: "👨‍⚕️", color: "#FCD34D" },
    { id: 517, label: "Hospital",        emoji: "🏥",  color: "#FCD34D" },
    { id: 518, label: "Ambulance",       emoji: "🚑",  color: "#FCD34D" },
    { id: 519, label: "Emergency",       emoji: "🆘",  color: "#FCD34D" },
    { id: 520, label: "Need Rest",       emoji: "🛌",  color: "#FCD34D" },
    { id: 521, label: "Tired/Fatigue",   emoji: "😩",  color: "#FCD34D" },
    { id: 522, label: "Feeling Better",  emoji: "😊",  color: "#FCD34D" },
    { id: 523, label: "Wheelchair",      emoji: "♿",  color: "#FCD34D" },
    { id: 524, label: "Therapy",         emoji: "🧠",  color: "#FCD34D" },
    { id: 525, label: "Eye Hurts",       emoji: "👁️", color: "#FCD34D" },
    { id: 526, label: "Knee Hurts",      emoji: "🦵",  color: "#FCD34D" },
    { id: 527, label: "Chest Hurts",     emoji: "💔",  color: "#FCD34D" },
    { id: 528, label: "Foot Hurts",      emoji: "🦶",  color: "#FCD34D" },
    { id: 529, label: "Allergic",        emoji: "🤧",  color: "#FCD34D" },
    { id: 530, label: "Bleeding",        emoji: "🩸",  color: "#FCD34D" },
    { id: 531, label: "Bruised",         emoji: "🟣",  color: "#FCD34D" },
    { id: 532, label: "Bandage",         emoji: "🩹",  color: "#FCD34D" },
    { id: 533, label: "Ice Pack",        emoji: "🧊",  color: "#FCD34D" },
    { id: 534, label: "Nosebleed",       emoji: "👃",  color: "#FCD34D" },
    { id: 535, label: "Hard to Breathe", emoji: "😮‍💨", color: "#FCD34D" },
    { id: 536, label: "Dentist",         emoji: "🦷",  color: "#FCD34D" },
  ],

  // ── Leisure (601–699) ─────────────────────────────────────────
  leisure: [
    { id: 601, label: "Play",            emoji: "🎮",  color: "#A78BFA" },
    { id: 602, label: "Read Book",       emoji: "📚",  color: "#A78BFA" },
    { id: 603, label: "Draw",            emoji: "🎨",  color: "#A78BFA" },
    { id: 604, label: "Color",           emoji: "🖍️", color: "#A78BFA" },
    { id: 605, label: "Music",           emoji: "🎵",  color: "#A78BFA" },
    { id: 606, label: "Sing",            emoji: "🎤",  color: "#A78BFA" },
    { id: 607, label: "Dance",           emoji: "🕺",  color: "#A78BFA" },
    { id: 608, label: "Watch TV",        emoji: "📺",  color: "#A78BFA" },
    { id: 609, label: "Movie",           emoji: "🎬",  color: "#A78BFA" },
    { id: 610, label: "Puzzle",          emoji: "🧩",  color: "#A78BFA" },
    { id: 611, label: "Board Game",      emoji: "🎲",  color: "#A78BFA" },
    { id: 612, label: "Lego/Blocks",     emoji: "🧱",  color: "#A78BFA" },
    { id: 613, label: "Doll",            emoji: "🪆",  color: "#A78BFA" },
    { id: 614, label: "Ball",            emoji: "⚽",  color: "#A78BFA" },
    { id: 615, label: "Bike",            emoji: "🚲",  color: "#A78BFA" },
    { id: 616, label: "Swim",            emoji: "🏊",  color: "#A78BFA" },
    { id: 617, label: "Run",             emoji: "🏃",  color: "#A78BFA" },
    { id: 618, label: "Playground",      emoji: "🛝",  color: "#A78BFA" },
    { id: 619, label: "Park",            emoji: "🌿",  color: "#A78BFA" },
    { id: 620, label: "Animals",         emoji: "🐾",  color: "#A78BFA" },
    { id: 621, label: "Craft",           emoji: "✂️",  color: "#A78BFA" },
    { id: 622, label: "Computer",        emoji: "💻",  color: "#A78BFA" },
    { id: 623, label: "Video Game",      emoji: "🕹️", color: "#A78BFA" },
    { id: 624, label: "Tablet",          emoji: "📱",  color: "#A78BFA" },
    { id: 625, label: "Trampoline",      emoji: "🤸",  color: "#A78BFA" },
    { id: 626, label: "Basketball",      emoji: "🏀",  color: "#A78BFA" },
    { id: 627, label: "Football",        emoji: "🏈",  color: "#A78BFA" },
    { id: 628, label: "Baseball",        emoji: "⚾",  color: "#A78BFA" },
    { id: 629, label: "Tennis",          emoji: "🎾",  color: "#A78BFA" },
    { id: 630, label: "Baking",          emoji: "🥧",  color: "#A78BFA" },
    { id: 631, label: "Gardening",       emoji: "🌱",  color: "#A78BFA" },
    { id: 632, label: "YouTube",         emoji: "▶️",  color: "#A78BFA" },
    { id: 633, label: "Stories",         emoji: "📖",  color: "#A78BFA" },
    { id: 634, label: "Photography",     emoji: "📷",  color: "#A78BFA" },
    { id: 635, label: "Karaoke",         emoji: "🎶",  color: "#A78BFA" },
  ],

  // ── School (701–799) ─────────────────────────────────────────
  school: [
    { id: 701, label: "School",          emoji: "🏫",  color: "#60A5FA" },
    { id: 702, label: "Class",           emoji: "🏛️", color: "#60A5FA" },
    { id: 703, label: "Teacher",         emoji: "👩‍🏫", color: "#60A5FA" },
    { id: 704, label: "Student",         emoji: "🧑‍🎓", color: "#60A5FA" },
    { id: 705, label: "Backpack",        emoji: "🎒",  color: "#60A5FA" },
    { id: 706, label: "Pencil",          emoji: "✏️",  color: "#60A5FA" },
    { id: 707, label: "Book",            emoji: "📖",  color: "#60A5FA" },
    { id: 708, label: "Notebook",        emoji: "📓",  color: "#60A5FA" },
    { id: 709, label: "Math",            emoji: "🔢",  color: "#60A5FA" },
    { id: 710, label: "Reading",         emoji: "📚",  color: "#60A5FA" },
    { id: 711, label: "Writing",         emoji: "✍️",  color: "#60A5FA" },
    { id: 712, label: "Art",             emoji: "🎨",  color: "#60A5FA" },
    { id: 713, label: "Music Class",     emoji: "🎵",  color: "#60A5FA" },
    { id: 714, label: "Gym/PE",          emoji: "🏋️", color: "#60A5FA" },
    { id: 715, label: "Lunch Break",     emoji: "🍱",  color: "#60A5FA" },
    { id: 716, label: "Recess",          emoji: "🛝",  color: "#60A5FA" },
    { id: 717, label: "Bus",             emoji: "🚌",  color: "#60A5FA" },
    { id: 718, label: "Homework",        emoji: "📝",  color: "#60A5FA" },
    { id: 719, label: "Test",            emoji: "📋",  color: "#60A5FA" },
    { id: 720, label: "Computer Lab",    emoji: "💻",  color: "#60A5FA" },
    { id: 721, label: "Library",         emoji: "📚",  color: "#60A5FA" },
    { id: 722, label: "Nurse",           emoji: "🩺",  color: "#60A5FA" },
    { id: 723, label: "Principal",       emoji: "🧑‍💼", color: "#60A5FA" },
    { id: 724, label: "Cafeteria",       emoji: "🍽️", color: "#60A5FA" },
    { id: 725, label: "Scissors",        emoji: "✂️",  color: "#60A5FA" },
    { id: 726, label: "Ruler",           emoji: "📏",  color: "#60A5FA" },
    { id: 727, label: "Crayons",         emoji: "🖍️", color: "#60A5FA" },
    { id: 728, label: "Glue",            emoji: "🫧",  color: "#60A5FA" },
    { id: 729, label: "Science",         emoji: "🔬",  color: "#60A5FA" },
    { id: 730, label: "History",         emoji: "🏛️", color: "#60A5FA" },
    { id: 731, label: "Geography",       emoji: "🌍",  color: "#60A5FA" },
    { id: 732, label: "Drama",           emoji: "🎭",  color: "#60A5FA" },
    { id: 733, label: "Calculator",      emoji: "🔢",  color: "#60A5FA" },
    { id: 734, label: "Hallway",         emoji: "🚶",  color: "#60A5FA" },
  ],

  // ── Places (801–899) ─────────────────────────────────────────
  places: [
    { id: 801, label: "Home",            emoji: "🏠",  color: "#34D399" },
    { id: 802, label: "Bedroom",         emoji: "🛏️", color: "#34D399" },
    { id: 803, label: "Kitchen",         emoji: "🍳",  color: "#34D399" },
    { id: 804, label: "Bathroom",        emoji: "🚿",  color: "#34D399" },
    { id: 805, label: "Living Room",     emoji: "🛋️", color: "#34D399" },
    { id: 806, label: "Backyard",        emoji: "🌱",  color: "#34D399" },
    { id: 807, label: "School",          emoji: "🏫",  color: "#34D399" },
    { id: 808, label: "Hospital",        emoji: "🏥",  color: "#34D399" },
    { id: 809, label: "Clinic",          emoji: "🩺",  color: "#34D399" },
    { id: 810, label: "Pharmacy",        emoji: "💊",  color: "#34D399" },
    { id: 811, label: "Grocery Store",   emoji: "🛒",  color: "#34D399" },
    { id: 812, label: "Restaurant",      emoji: "🍽️", color: "#34D399" },
    { id: 813, label: "Park",            emoji: "🌿",  color: "#34D399" },
    { id: 814, label: "Playground",      emoji: "🛝",  color: "#34D399" },
    { id: 815, label: "Library",         emoji: "📚",  color: "#34D399" },
    { id: 816, label: "Church",          emoji: "⛪",  color: "#34D399" },
    { id: 817, label: "Gym",             emoji: "🏋️", color: "#34D399" },
    { id: 818, label: "Pool",            emoji: "🏊",  color: "#34D399" },
    { id: 819, label: "Beach",           emoji: "🏖️", color: "#34D399" },
    { id: 820, label: "Car",             emoji: "🚗",  color: "#34D399" },
    { id: 821, label: "Bus Stop",        emoji: "🚌",  color: "#34D399" },
    { id: 822, label: "Airport",         emoji: "✈️",  color: "#34D399" },
    { id: 823, label: "Dentist",         emoji: "🦷",  color: "#34D399" },
    { id: 824, label: "Therapy",         emoji: "🧠",  color: "#34D399" },
    { id: 825, label: "Mall",            emoji: "🏬",  color: "#34D399" },
    { id: 826, label: "Movie Theater",   emoji: "🎬",  color: "#34D399" },
    { id: 827, label: "Zoo",             emoji: "🦁",  color: "#34D399" },
    { id: 828, label: "Aquarium",        emoji: "🐠",  color: "#34D399" },
    { id: 829, label: "Museum",          emoji: "🏛️", color: "#34D399" },
    { id: 830, label: "Amusement Park",  emoji: "🎡",  color: "#34D399" },
    { id: 831, label: "Gas Station",     emoji: "⛽",  color: "#34D399" },
    { id: 832, label: "Post Office",     emoji: "📮",  color: "#34D399" },
    { id: 833, label: "Fire Station",    emoji: "🚒",  color: "#34D399" },
    { id: 834, label: "Barbershop",      emoji: "💈",  color: "#34D399" },
  ],

  // ── People (901–999) ─────────────────────────────────────────
  people: [
    { id: 901, label: "Me",              emoji: "🙋",  color: "#F472B6" },
    { id: 902, label: "Mom",             emoji: "👩",  color: "#F472B6" },
    { id: 903, label: "Dad",             emoji: "👨",  color: "#F472B6" },
    { id: 904, label: "Grandma",         emoji: "👵",  color: "#F472B6" },
    { id: 905, label: "Grandpa",         emoji: "👴",  color: "#F472B6" },
    { id: 906, label: "Brother",         emoji: "👦",  color: "#F472B6" },
    { id: 907, label: "Sister",          emoji: "👧",  color: "#F472B6" },
    { id: 908, label: "Baby",            emoji: "👶",  color: "#F472B6" },
    { id: 909, label: "Family",          emoji: "👨‍👩‍👧‍👦", color: "#F472B6" },
    { id: 910, label: "Friend",          emoji: "🧑",  color: "#F472B6" },
    { id: 911, label: "Best Friend",     emoji: "🫂",  color: "#F472B6" },
    { id: 912, label: "Caregiver",       emoji: "🧑‍🦽", color: "#F472B6" },
    { id: 913, label: "Doctor",          emoji: "👨‍⚕️", color: "#F472B6" },
    { id: 914, label: "Nurse",           emoji: "👩‍⚕️", color: "#F472B6" },
    { id: 915, label: "Teacher",         emoji: "👩‍🏫", color: "#F472B6" },
    { id: 916, label: "Therapist",       emoji: "🧠",  color: "#F472B6" },
    { id: 917, label: "Neighbor",        emoji: "🏘️", color: "#F472B6" },
    { id: 918, label: "Classmate",       emoji: "🧑‍🎓", color: "#F472B6" },
    { id: 919, label: "Coach",           emoji: "🏅",  color: "#F472B6" },
    { id: 920, label: "Aunt",            emoji: "👩‍🦰", color: "#F472B6" },
    { id: 921, label: "Uncle",           emoji: "👨‍🦰", color: "#F472B6" },
    { id: 922, label: "Pet",             emoji: "🐶",  color: "#F472B6" },
    { id: 923, label: "Cousin",          emoji: "🧒",  color: "#F472B6" },
    { id: 924, label: "Aide",            emoji: "🤝",  color: "#F472B6" },
    { id: 925, label: "Bus Driver",      emoji: "🚌",  color: "#F472B6" },
    { id: 926, label: "Librarian",       emoji: "📚",  color: "#F472B6" },
    { id: 927, label: "Everyone",        emoji: "👥",  color: "#F472B6" },
    { id: 928, label: "Nobody",          emoji: "🚫",  color: "#F472B6" },
  ],

  // ── Needs & Requests (1001–1099) ─────────────────────────────
  needs: [
    { id: 1001, label: "I Want",          emoji: "🫳",  color: "#C4B5FD" },
    { id: 1002, label: "I Need",          emoji: "❗",  color: "#C4B5FD" },
    { id: 1003, label: "I Like",          emoji: "❤️",  color: "#C4B5FD" },
    { id: 1004, label: "I Don't Like",    emoji: "👎",  color: "#C4B5FD" },
    { id: 1005, label: "Give Me",         emoji: "🙌",  color: "#C4B5FD" },
    { id: 1006, label: "Take Away",       emoji: "↩️",  color: "#C4B5FD" },
    { id: 1007, label: "Too Loud",        emoji: "🔇",  color: "#C4B5FD" },
    { id: 1008, label: "Too Quiet",       emoji: "🔊",  color: "#C4B5FD" },
    { id: 1009, label: "Too Hot",         emoji: "🔥",  color: "#C4B5FD" },
    { id: 1010, label: "Too Cold",        emoji: "❄️",  color: "#C4B5FD" },
    { id: 1011, label: "Comfortable",     emoji: "😌",  color: "#C4B5FD" },
    { id: 1012, label: "Uncomfortable",   emoji: "😫",  color: "#C4B5FD" },
    { id: 1013, label: "Turn On",         emoji: "💡",  color: "#C4B5FD" },
    { id: 1014, label: "Turn Off",        emoji: "🌑",  color: "#C4B5FD" },
    { id: 1015, label: "Open",            emoji: "🔓",  color: "#C4B5FD" },
    { id: 1016, label: "Close",           emoji: "🔐",  color: "#C4B5FD" },
    { id: 1017, label: "Sit Down",        emoji: "🪑",  color: "#C4B5FD" },
    { id: 1018, label: "Stand Up",        emoji: "🧍",  color: "#C4B5FD" },
    { id: 1019, label: "Lie Down",        emoji: "🛌",  color: "#C4B5FD" },
    { id: 1020, label: "Go Away",         emoji: "🚷",  color: "#C4B5FD" },
    { id: 1021, label: "Come Back",       emoji: "↩️",  color: "#C4B5FD" },
    { id: 1022, label: "Hug Me",          emoji: "🤗",  color: "#C4B5FD" },
    { id: 1023, label: "Leave Me",        emoji: "✋",  color: "#C4B5FD" },
    { id: 1024, label: "Change It",       emoji: "🔄",  color: "#C4B5FD" },
    { id: 1025, label: "Too Bright",      emoji: "🌟",  color: "#C4B5FD" },
    { id: 1026, label: "Too Dark",        emoji: "🌑",  color: "#C4B5FD" },
    { id: 1027, label: "Too Fast",        emoji: "⚡",  color: "#C4B5FD" },
    { id: 1028, label: "Too Slow",        emoji: "🐢",  color: "#C4B5FD" },
    { id: 1029, label: "Not Enough",      emoji: "📉",  color: "#C4B5FD" },
    { id: 1030, label: "Too Much",        emoji: "📈",  color: "#C4B5FD" },
    { id: 1031, label: "Show Me",         emoji: "👆",  color: "#C4B5FD" },
    { id: 1032, label: "Help Me Up",      emoji: "🙋",  color: "#C4B5FD" },
    { id: 1033, label: "Fix It",          emoji: "🔧",  color: "#C4B5FD" },
    { id: 1034, label: "All Done",        emoji: "🏁",  color: "#C4B5FD" },
    { id: 1035, label: "Wait for Me",     emoji: "🐌",  color: "#C4B5FD" },
    { id: 1036, label: "Repeat Please",   emoji: "🔁",  color: "#C4B5FD" },
  ],

  // ── Actions / Verbs (1101–1199) ──────────────────────────────
  actions: [
    { id: 1101, label: "Go",             emoji: "🚶",  color: "#FB923C" },
    { id: 1102, label: "Come",           emoji: "🫵",  color: "#FB923C" },
    { id: 1103, label: "Sit",            emoji: "🪑",  color: "#FB923C" },
    { id: 1104, label: "Stand",          emoji: "🧍",  color: "#FB923C" },
    { id: 1105, label: "Walk",           emoji: "🚶",  color: "#FB923C" },
    { id: 1106, label: "Run",            emoji: "🏃",  color: "#FB923C" },
    { id: 1107, label: "Stop",           emoji: "✋",  color: "#FB923C" },
    { id: 1108, label: "Eat",            emoji: "🍽️", color: "#FB923C" },
    { id: 1109, label: "Drink",          emoji: "🥤",  color: "#FB923C" },
    { id: 1110, label: "Sleep",          emoji: "😴",  color: "#FB923C" },
    { id: 1111, label: "Play",           emoji: "🎮",  color: "#FB923C" },
    { id: 1112, label: "Talk",           emoji: "💬",  color: "#FB923C" },
    { id: 1113, label: "Listen",         emoji: "👂",  color: "#FB923C" },
    { id: 1114, label: "Look",           emoji: "👀",  color: "#FB923C" },
    { id: 1115, label: "Help",           emoji: "🤝",  color: "#FB923C" },
    { id: 1116, label: "Give",           emoji: "🤲",  color: "#FB923C" },
    { id: 1117, label: "Take",           emoji: "🫴",  color: "#FB923C" },
    { id: 1118, label: "Open",           emoji: "📂",  color: "#FB923C" },
    { id: 1119, label: "Close",          emoji: "📁",  color: "#FB923C" },
    { id: 1120, label: "Wash",           emoji: "🧼",  color: "#FB923C" },
    { id: 1121, label: "Get",            emoji: "🫳",  color: "#FB923C" },
    { id: 1122, label: "Put",            emoji: "📥",  color: "#FB923C" },
    { id: 1123, label: "Make",           emoji: "🔨",  color: "#FB923C" },
    { id: 1124, label: "Find",           emoji: "🔍",  color: "#FB923C" },
    { id: 1125, label: "Show",           emoji: "🫵",  color: "#FB923C" },
    { id: 1126, label: "Tell",           emoji: "📢",  color: "#FB923C" },
    { id: 1127, label: "Ask",            emoji: "❓",  color: "#FB923C" },
    { id: 1128, label: "Answer",         emoji: "💡",  color: "#FB923C" },
    { id: 1129, label: "Choose",         emoji: "☑️",  color: "#FB923C" },
    { id: 1130, label: "Read",           emoji: "📖",  color: "#FB923C" },
    { id: 1131, label: "Write",          emoji: "✏️",  color: "#FB923C" },
    { id: 1132, label: "Draw",           emoji: "🖍️", color: "#FB923C" },
    { id: 1133, label: "Sing",           emoji: "🎵",  color: "#FB923C" },
    { id: 1134, label: "Dance",          emoji: "💃",  color: "#FB923C" },
    { id: 1135, label: "Jump",           emoji: "⬆️",  color: "#FB923C" },
    { id: 1136, label: "Push",           emoji: "🫷",  color: "#FB923C" },
    { id: 1137, label: "Pull",           emoji: "🫸",  color: "#FB923C" },
    { id: 1138, label: "Touch",          emoji: "👆",  color: "#FB923C" },
    { id: 1139, label: "Point",          emoji: "☝️",  color: "#FB923C" },
    { id: 1140, label: "Turn",           emoji: "🔄",  color: "#FB923C" },
    { id: 1141, label: "Try",            emoji: "💪",  color: "#FB923C" },
    { id: 1142, label: "Finish",         emoji: "🏁",  color: "#FB923C" },
    { id: 1143, label: "Start",          emoji: "▶️",  color: "#FB923C" },
    { id: 1144, label: "Wait",           emoji: "⏳",  color: "#FB923C" },
    { id: 1145, label: "Think",          emoji: "🤔",  color: "#FB923C" },
    { id: 1146, label: "Remember",       emoji: "🧠",  color: "#FB923C" },
    { id: 1147, label: "Count",          emoji: "🔢",  color: "#FB923C" },
    { id: 1148, label: "Hug",            emoji: "🤗",  color: "#FB923C" },
    { id: 1149, label: "Laugh",          emoji: "😂",  color: "#FB923C" },
    { id: 1150, label: "Cry",            emoji: "😭",  color: "#FB923C" },
    { id: 1151, label: "Smile",          emoji: "😊",  color: "#FB923C" },
    { id: 1152, label: "Clap",           emoji: "👏",  color: "#FB923C" },
    { id: 1153, label: "Wave",           emoji: "👋",  color: "#FB923C" },
    { id: 1154, label: "Cook",           emoji: "🍳",  color: "#FB923C" },
    { id: 1155, label: "Clean",          emoji: "🧹",  color: "#FB923C" },
    { id: 1156, label: "Share",          emoji: "🤲",  color: "#FB923C" },
    { id: 1157, label: "Buy",            emoji: "🛒",  color: "#FB923C" },
    { id: 1158, label: "Pay",            emoji: "💳",  color: "#FB923C" },
    { id: 1159, label: "Call",           emoji: "📞",  color: "#FB923C" },
    { id: 1160, label: "Watch",          emoji: "📺",  color: "#FB923C" },
  ],

  // ── Questions (1201–1299) ────────────────────────────────────
  questions: [
    { id: 1201, label: "What",           emoji: "❓",  color: "#38BDF8" },
    { id: 1202, label: "Where",          emoji: "📍",  color: "#38BDF8" },
    { id: 1203, label: "When",           emoji: "🕐",  color: "#38BDF8" },
    { id: 1204, label: "Who",            emoji: "🙋",  color: "#38BDF8" },
    { id: 1205, label: "Why",            emoji: "🤔",  color: "#38BDF8" },
    { id: 1206, label: "How",            emoji: "💡",  color: "#38BDF8" },
    { id: 1207, label: "How Much",       emoji: "💰",  color: "#38BDF8" },
    { id: 1208, label: "How Many",       emoji: "🔢",  color: "#38BDF8" },
    { id: 1209, label: "Which One",      emoji: "☝️",  color: "#38BDF8" },
    { id: 1210, label: "Can I",          emoji: "🙋",  color: "#38BDF8" },
    { id: 1211, label: "Do You",         emoji: "👤",  color: "#38BDF8" },
    { id: 1212, label: "Is It",          emoji: "🔍",  color: "#38BDF8" },
    { id: 1213, label: "Are You",        emoji: "👀",  color: "#38BDF8" },
    { id: 1214, label: "Will You",       emoji: "🤝",  color: "#38BDF8" },
    { id: 1215, label: "What Time",      emoji: "⏰",  color: "#38BDF8" },
    { id: 1216, label: "What Day",       emoji: "📅",  color: "#38BDF8" },
    { id: 1217, label: "Where Is",       emoji: "🗺️", color: "#38BDF8" },
    { id: 1218, label: "Who Is",         emoji: "👥",  color: "#38BDF8" },
    { id: 1219, label: "What Is",        emoji: "📌",  color: "#38BDF8" },
    { id: 1220, label: "What Happened",  emoji: "😮",  color: "#38BDF8" },
    { id: 1221, label: "Are We Going",   emoji: "🚶",  color: "#38BDF8" },
    { id: 1222, label: "How Long",       emoji: "⏱️", color: "#38BDF8" },
    { id: 1223, label: "How Often",      emoji: "🔁",  color: "#38BDF8" },
    { id: 1224, label: "What Next",      emoji: "➡️",  color: "#38BDF8" },
    { id: 1225, label: "Why Not",        emoji: "🚫",  color: "#38BDF8" },
  ],

  // ── Colours (1301–1399) ──────────────────────────────────────
  colours: [
    { id: 1301, label: "Red",            emoji: "🔴",  color: "#EF4444" },
    { id: 1302, label: "Orange",         emoji: "🟠",  color: "#FB923C" },
    { id: 1303, label: "Yellow",         emoji: "🟡",  color: "#FACC15" },
    { id: 1304, label: "Green",          emoji: "🟢",  color: "#22C55E" },
    { id: 1305, label: "Blue",           emoji: "🔵",  color: "#3B82F6" },
    { id: 1306, label: "Purple",         emoji: "🟣",  color: "#A855F7" },
    { id: 1307, label: "Pink",           emoji: "🩷",  color: "#EC4899" },
    { id: 1308, label: "Brown",          emoji: "🟤",  color: "#92400E" },
    { id: 1309, label: "Black",          emoji: "⚫",  color: "#374151" },
    { id: 1310, label: "White",          emoji: "⚪",  color: "#94A3B8" },
    { id: 1311, label: "Grey",           emoji: "🩶",  color: "#6B7280" },
    { id: 1312, label: "Gold",           emoji: "🥇",  color: "#D97706" },
    { id: 1313, label: "Silver",         emoji: "🥈",  color: "#9CA3AF" },
    { id: 1314, label: "Teal",           emoji: "🩵",  color: "#0D9488" },
    { id: 1315, label: "Navy",           emoji: "💙",  color: "#1E3A8A" },
    { id: 1316, label: "Lime",           emoji: "💚",  color: "#65A30D" },
    { id: 1317, label: "Rainbow",        emoji: "🌈",  color: "#6366F1" },
    { id: 1318, label: "Dark",           emoji: "🌑",  color: "#374151" },
    { id: 1319, label: "Light",          emoji: "🌕",  color: "#FDE68A" },
    { id: 1320, label: "Beige",          emoji: "🟫",  color: "#D97706" },
  ],

  // ── Numbers & Time (1401–1499) ───────────────────────────────
  time: [
    { id: 1401, label: "1 One",          emoji: "1️⃣", color: "#818CF8" },
    { id: 1402, label: "2 Two",          emoji: "2️⃣", color: "#818CF8" },
    { id: 1403, label: "3 Three",        emoji: "3️⃣", color: "#818CF8" },
    { id: 1404, label: "4 Four",         emoji: "4️⃣", color: "#818CF8" },
    { id: 1405, label: "5 Five",         emoji: "5️⃣", color: "#818CF8" },
    { id: 1406, label: "6 Six",          emoji: "6️⃣", color: "#818CF8" },
    { id: 1407, label: "7 Seven",        emoji: "7️⃣", color: "#818CF8" },
    { id: 1408, label: "8 Eight",        emoji: "8️⃣", color: "#818CF8" },
    { id: 1409, label: "9 Nine",         emoji: "9️⃣", color: "#818CF8" },
    { id: 1410, label: "10 Ten",         emoji: "🔟",  color: "#818CF8" },
    { id: 1411, label: "Today",          emoji: "📅",  color: "#818CF8" },
    { id: 1412, label: "Tomorrow",       emoji: "⏭️", color: "#818CF8" },
    { id: 1413, label: "Yesterday",      emoji: "⏮️", color: "#818CF8" },
    { id: 1414, label: "Morning",        emoji: "🌅",  color: "#818CF8" },
    { id: 1415, label: "Afternoon",      emoji: "☀️",  color: "#818CF8" },
    { id: 1416, label: "Evening",        emoji: "🌆",  color: "#818CF8" },
    { id: 1417, label: "Night",          emoji: "🌙",  color: "#818CF8" },
    { id: 1418, label: "Now",            emoji: "⚡",  color: "#818CF8" },
    { id: 1419, label: "Later",          emoji: "⏰",  color: "#818CF8" },
    { id: 1420, label: "Soon",           emoji: "🔜",  color: "#818CF8" },
    { id: 1421, label: "Monday",         emoji: "📆",  color: "#818CF8" },
    { id: 1422, label: "Tuesday",        emoji: "📆",  color: "#818CF8" },
    { id: 1423, label: "Wednesday",      emoji: "📆",  color: "#818CF8" },
    { id: 1424, label: "Thursday",       emoji: "📆",  color: "#818CF8" },
    { id: 1425, label: "Friday",         emoji: "🎉",  color: "#818CF8" },
    { id: 1426, label: "Saturday",       emoji: "🏖️", color: "#818CF8" },
    { id: 1427, label: "Sunday",         emoji: "⛪",  color: "#818CF8" },
    { id: 1428, label: "This Week",      emoji: "📅",  color: "#818CF8" },
    { id: 1429, label: "Next Week",      emoji: "➡️",  color: "#818CF8" },
    { id: 1430, label: "Always",         emoji: "♾️",  color: "#818CF8" },
    { id: 1431, label: "Never",          emoji: "🚫",  color: "#818CF8" },
    { id: 1432, label: "Sometimes",      emoji: "🔄",  color: "#818CF8" },
    { id: 1433, label: "Every Day",      emoji: "🌞",  color: "#818CF8" },
    { id: 1434, label: "A Long Time",    emoji: "⏳",  color: "#818CF8" },
    { id: 1435, label: "A Short Time",   emoji: "⏱️", color: "#818CF8" },
  ],

  // ── Animals (1501–1599) ──────────────────────────────────────
  animals: [
    { id: 1501, label: "Dog",            emoji: "🐶",  color: "#A3E635" },
    { id: 1502, label: "Cat",            emoji: "🐱",  color: "#A3E635" },
    { id: 1503, label: "Bird",           emoji: "🐦",  color: "#A3E635" },
    { id: 1504, label: "Fish",           emoji: "🐟",  color: "#A3E635" },
    { id: 1505, label: "Rabbit",         emoji: "🐰",  color: "#A3E635" },
    { id: 1506, label: "Hamster",        emoji: "🐹",  color: "#A3E635" },
    { id: 1507, label: "Horse",          emoji: "🐴",  color: "#A3E635" },
    { id: 1508, label: "Cow",            emoji: "🐮",  color: "#A3E635" },
    { id: 1509, label: "Pig",            emoji: "🐷",  color: "#A3E635" },
    { id: 1510, label: "Chicken",        emoji: "🐔",  color: "#A3E635" },
    { id: 1511, label: "Duck",           emoji: "🦆",  color: "#A3E635" },
    { id: 1512, label: "Lion",           emoji: "🦁",  color: "#A3E635" },
    { id: 1513, label: "Elephant",       emoji: "🐘",  color: "#A3E635" },
    { id: 1514, label: "Giraffe",        emoji: "🦒",  color: "#A3E635" },
    { id: 1515, label: "Monkey",         emoji: "🐵",  color: "#A3E635" },
    { id: 1516, label: "Bear",           emoji: "🐻",  color: "#A3E635" },
    { id: 1517, label: "Turtle",         emoji: "🐢",  color: "#A3E635" },
    { id: 1518, label: "Frog",           emoji: "🐸",  color: "#A3E635" },
    { id: 1519, label: "Snake",          emoji: "🐍",  color: "#A3E635" },
    { id: 1520, label: "Butterfly",      emoji: "🦋",  color: "#A3E635" },
    { id: 1521, label: "Bee",            emoji: "🐝",  color: "#A3E635" },
    { id: 1522, label: "Deer",           emoji: "🦌",  color: "#A3E635" },
    { id: 1523, label: "Owl",            emoji: "🦉",  color: "#A3E635" },
    { id: 1524, label: "Parrot",         emoji: "🦜",  color: "#A3E635" },
    { id: 1525, label: "Whale",          emoji: "🐋",  color: "#A3E635" },
    { id: 1526, label: "Shark",          emoji: "🦈",  color: "#A3E635" },
    { id: 1527, label: "Crab",           emoji: "🦀",  color: "#A3E635" },
    { id: 1528, label: "Squirrel",       emoji: "🐿️", color: "#A3E635" },
    { id: 1529, label: "Dinosaur",       emoji: "🦕",  color: "#A3E635" },
    { id: 1530, label: "Unicorn",        emoji: "🦄",  color: "#A3E635" },
    { id: 1531, label: "Penguin",        emoji: "🐧",  color: "#A3E635" },
    { id: 1532, label: "Fox",            emoji: "🦊",  color: "#A3E635" },
    { id: 1533, label: "Tiger",          emoji: "🐯",  color: "#A3E635" },
    { id: 1534, label: "Koala",          emoji: "🐨",  color: "#A3E635" },
    { id: 1535, label: "Panda",          emoji: "🐼",  color: "#A3E635" },
  ],

  // ── Clothing (1601–1699) ─────────────────────────────────────
  clothing: [
    { id: 1601, label: "Shirt",          emoji: "👕",  color: "#FB7185" },
    { id: 1602, label: "Pants",          emoji: "👖",  color: "#FB7185" },
    { id: 1603, label: "Dress",          emoji: "👗",  color: "#FB7185" },
    { id: 1604, label: "Skirt",          emoji: "🩱",  color: "#FB7185" },
    { id: 1605, label: "Shoes",          emoji: "👟",  color: "#FB7185" },
    { id: 1606, label: "Socks",          emoji: "🧦",  color: "#FB7185" },
    { id: 1607, label: "Hat",            emoji: "🧢",  color: "#FB7185" },
    { id: 1608, label: "Coat",           emoji: "🧥",  color: "#FB7185" },
    { id: 1609, label: "Gloves",         emoji: "🧤",  color: "#FB7185" },
    { id: 1610, label: "Boots",          emoji: "👢",  color: "#FB7185" },
    { id: 1611, label: "Pyjamas",        emoji: "🌙",  color: "#FB7185" },
    { id: 1612, label: "Underwear",      emoji: "🩲",  color: "#FB7185" },
    { id: 1613, label: "Swimsuit",       emoji: "🩳",  color: "#FB7185" },
    { id: 1614, label: "Scarf",          emoji: "🧣",  color: "#FB7185" },
    { id: 1615, label: "Jeans",          emoji: "👖",  color: "#FB7185" },
    { id: 1616, label: "Sweater",        emoji: "🧶",  color: "#FB7185" },
    { id: 1617, label: "Shorts",         emoji: "🩳",  color: "#FB7185" },
    { id: 1618, label: "Hoodie",         emoji: "👕",  color: "#FB7185" },
    { id: 1619, label: "Slippers",       emoji: "🥿",  color: "#FB7185" },
    { id: 1620, label: "Sandals",        emoji: "👡",  color: "#FB7185" },
    { id: 1621, label: "Raincoat",       emoji: "🌧️", color: "#FB7185" },
    { id: 1622, label: "Mittens",        emoji: "🧤",  color: "#FB7185" },
    { id: 1623, label: "Sunglasses",     emoji: "🕶️", color: "#FB7185" },
    { id: 1624, label: "Glasses",        emoji: "👓",  color: "#FB7185" },
    { id: 1625, label: "Hearing Aid",    emoji: "👂",  color: "#FB7185" },
    { id: 1626, label: "Bib",            emoji: "🥄",  color: "#FB7185" },
    { id: 1627, label: "Diaper",         emoji: "🍼",  color: "#FB7185" },
    { id: 1628, label: "Backpack",       emoji: "🎒",  color: "#FB7185" },
    { id: 1629, label: "Jacket",         emoji: "🧥",  color: "#FB7185" },
  ],

  // ── Body Parts (1701–1799) ───────────────────────────────────
  body: [
    { id: 1701, label: "Head",           emoji: "👤",  color: "#F0ABFC" },
    { id: 1702, label: "Hair",           emoji: "💇",  color: "#F0ABFC" },
    { id: 1703, label: "Eye",            emoji: "👁️", color: "#F0ABFC" },
    { id: 1704, label: "Ear",            emoji: "👂",  color: "#F0ABFC" },
    { id: 1705, label: "Nose",           emoji: "👃",  color: "#F0ABFC" },
    { id: 1706, label: "Mouth",          emoji: "👄",  color: "#F0ABFC" },
    { id: 1707, label: "Teeth",          emoji: "🦷",  color: "#F0ABFC" },
    { id: 1708, label: "Tongue",         emoji: "👅",  color: "#F0ABFC" },
    { id: 1709, label: "Neck",           emoji: "🦒",  color: "#F0ABFC" },
    { id: 1710, label: "Shoulder",       emoji: "🤷",  color: "#F0ABFC" },
    { id: 1711, label: "Arm",            emoji: "💪",  color: "#F0ABFC" },
    { id: 1712, label: "Elbow",          emoji: "🦾",  color: "#F0ABFC" },
    { id: 1713, label: "Hand",           emoji: "🖐️", color: "#F0ABFC" },
    { id: 1714, label: "Finger",         emoji: "☝️",  color: "#F0ABFC" },
    { id: 1715, label: "Thumb",          emoji: "👍",  color: "#F0ABFC" },
    { id: 1716, label: "Chest",          emoji: "🫀",  color: "#F0ABFC" },
    { id: 1717, label: "Tummy",          emoji: "🫃",  color: "#F0ABFC" },
    { id: 1718, label: "Back",           emoji: "🦴",  color: "#F0ABFC" },
    { id: 1719, label: "Leg",            emoji: "🦵",  color: "#F0ABFC" },
    { id: 1720, label: "Knee",           emoji: "🦵",  color: "#F0ABFC" },
    { id: 1721, label: "Foot",           emoji: "🦶",  color: "#F0ABFC" },
    { id: 1722, label: "Toe",            emoji: "🦶",  color: "#F0ABFC" },
    { id: 1723, label: "Face",           emoji: "😊",  color: "#F0ABFC" },
    { id: 1724, label: "Cheek",          emoji: "😊",  color: "#F0ABFC" },
    { id: 1725, label: "Forehead",       emoji: "🤔",  color: "#F0ABFC" },
    { id: 1726, label: "Wrist",          emoji: "⌚",  color: "#F0ABFC" },
    { id: 1727, label: "Ankle",          emoji: "🦶",  color: "#F0ABFC" },
    { id: 1728, label: "Heart",          emoji: "❤️",  color: "#F0ABFC" },
    { id: 1729, label: "Brain",          emoji: "🧠",  color: "#F0ABFC" },
    { id: 1730, label: "Lungs",          emoji: "🫁",  color: "#F0ABFC" },
    { id: 1731, label: "Skin",           emoji: "✋",  color: "#F0ABFC" },
    { id: 1732, label: "Hip",            emoji: "🦵",  color: "#F0ABFC" },
  ],

  // ── Weather (1801–1899) ──────────────────────────────────────
  weather: [
    { id: 1801, label: "Sunny",          emoji: "☀️",  color: "#FDE047" },
    { id: 1802, label: "Cloudy",         emoji: "☁️",  color: "#FDE047" },
    { id: 1803, label: "Rainy",          emoji: "🌧️", color: "#FDE047" },
    { id: 1804, label: "Windy",          emoji: "💨",  color: "#FDE047" },
    { id: 1805, label: "Snowy",          emoji: "❄️",  color: "#FDE047" },
    { id: 1806, label: "Stormy",         emoji: "⛈️", color: "#FDE047" },
    { id: 1807, label: "Hot",            emoji: "🌡️", color: "#FDE047" },
    { id: 1808, label: "Cold",           emoji: "🥶",  color: "#FDE047" },
    { id: 1809, label: "Warm",           emoji: "🌤️", color: "#FDE047" },
    { id: 1810, label: "Cool",           emoji: "🌬️", color: "#FDE047" },
    { id: 1811, label: "Foggy",          emoji: "🌫️", color: "#FDE047" },
    { id: 1812, label: "Thunder",        emoji: "🌩️", color: "#FDE047" },
    { id: 1813, label: "Lightning",      emoji: "⚡",  color: "#FDE047" },
    { id: 1814, label: "Rainbow",        emoji: "🌈",  color: "#FDE047" },
    { id: 1815, label: "Hail",           emoji: "🌨️", color: "#FDE047" },
    { id: 1816, label: "Icy",            emoji: "🧊",  color: "#FDE047" },
    { id: 1817, label: "Humid",          emoji: "💧",  color: "#FDE047" },
    { id: 1818, label: "Partly Cloudy",  emoji: "⛅",  color: "#FDE047" },
    { id: 1819, label: "Blizzard",       emoji: "🌨️", color: "#FDE047" },
    { id: 1820, label: "Spring",         emoji: "🌸",  color: "#FDE047" },
    { id: 1821, label: "Summer",         emoji: "🏖️", color: "#FDE047" },
    { id: 1822, label: "Autumn",         emoji: "🍂",  color: "#FDE047" },
    { id: 1823, label: "Winter",         emoji: "⛄",  color: "#FDE047" },
    { id: 1824, label: "Sunrise",        emoji: "🌅",  color: "#FDE047" },
    { id: 1825, label: "Sunset",         emoji: "🌇",  color: "#FDE047" },
  ],

  // ── Transport (1901–1999) ────────────────────────────────────
  transport: [
    { id: 1901, label: "Car",            emoji: "🚗",  color: "#4ADE80" },
    { id: 1902, label: "Bus",            emoji: "🚌",  color: "#4ADE80" },
    { id: 1903, label: "Train",          emoji: "🚆",  color: "#4ADE80" },
    { id: 1904, label: "Airplane",       emoji: "✈️",  color: "#4ADE80" },
    { id: 1905, label: "Bike",           emoji: "🚲",  color: "#4ADE80" },
    { id: 1906, label: "Taxi",           emoji: "🚕",  color: "#4ADE80" },
    { id: 1907, label: "Boat",           emoji: "⛵",  color: "#4ADE80" },
    { id: 1908, label: "Helicopter",     emoji: "🚁",  color: "#4ADE80" },
    { id: 1909, label: "Motorcycle",     emoji: "🏍️", color: "#4ADE80" },
    { id: 1910, label: "Scooter",        emoji: "🛴",  color: "#4ADE80" },
    { id: 1911, label: "Ambulance",      emoji: "🚑",  color: "#4ADE80" },
    { id: 1912, label: "Fire Truck",     emoji: "🚒",  color: "#4ADE80" },
    { id: 1913, label: "Police Car",     emoji: "🚓",  color: "#4ADE80" },
    { id: 1914, label: "Subway",         emoji: "🚇",  color: "#4ADE80" },
    { id: 1915, label: "Van",            emoji: "🚐",  color: "#4ADE80" },
    { id: 1916, label: "Truck",          emoji: "🚛",  color: "#4ADE80" },
    { id: 1917, label: "Skateboard",     emoji: "🛹",  color: "#4ADE80" },
    { id: 1918, label: "Walk",           emoji: "🚶",  color: "#4ADE80" },
    { id: 1919, label: "Wheelchair",     emoji: "♿",  color: "#4ADE80" },
    { id: 1920, label: "School Bus",     emoji: "🚌",  color: "#4ADE80" },
    { id: 1921, label: "Rocket",         emoji: "🚀",  color: "#4ADE80" },
    { id: 1922, label: "Ferry",          emoji: "⛴️", color: "#4ADE80" },
    { id: 1923, label: "Carpool",        emoji: "🚗",  color: "#4ADE80" },
  ],

};

export const getAllSymbols = () => Object.values(EMOJI_SYMBOLS).flat();
